name: 'Auto Changelog Entry'
description: 'Automatically adds a changelog entry to a specified file when PR is merged.'
inputs:
  config-file-path:
    description: 'Path to the configuration file'
    required: true
    default: '.github/auto_changelog_config.yml'
  ignore-label:
    description: 'Label that skips the execution if present'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'