name: 'Auto Changelog Entry'
description: 'Automatically adds a changelog entry to a specified file when PR is merged.'
inputs:
  changelog-file:
    description: 'Changelog file to use'
    required: true
    default: 'CHANGELOG.md'
  template:
    description: 'Template for the changelog entry'
    required: true
    default: '$TITLE'
  ignore-label:
    description: 'Label that skips the execution if present'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'